# Generated by Django 2.0.3 on 2018-03-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yt_id', models.CharField(max_length=200)),
                ('name', models.CharField(default=None, max_length=300)),
                ('creator_username', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yt_id', models.CharField(max_length=200)),
                ('title', models.CharField(default=None, max_length=300)),
                ('downloaded', models.BooleanField(default=False)),
                ('converted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='videos',
            field=models.ManyToManyField(to='videos.Video'),
        ),
    ]
