# Generated by Django 2.0.3 on 2018-03-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='parsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
