# Generated by Django 2.0.3 on 2018-03-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20180310_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='processing',
            field=models.BooleanField(default=False),
        ),
    ]
