# Generated by Django 2.0.3 on 2018-04-05 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_processing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='videos',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
