# Generated by Django 2.0.3 on 2018-04-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0004_auto_20180405_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yt_id', models.CharField(max_length=200)),
                ('name', models.CharField(default=None, max_length=300)),
                ('creator_username', models.CharField(max_length=200)),
                ('videos', models.ManyToManyField(to='videos.Video')),
            ],
        ),
    ]
